version: '3.8'
services:
  tradingapp:
    build:
      context: TradingApp
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest     
    ports:
      - "1433:1433"
    env_file:
      - .env
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  pythonservice:
    build:
      context: server
    environment:
      PYTHON_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro